force-app/main/default/objects/KicksawEng__IntegrationExecution__c/fields/Next_Retry_Scheduled__c.field-meta.xml
<CustomField>
    <fullName>Next_Retry_Scheduled__c</fullName>
    <label>Next Retry Scheduled</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/KicksawEng__IntegrationExecution__c/fields/Record_Id__c.field-meta.xml
<CustomField>
    <fullName>Record_Id__c</fullName>
    <description>If the integration execution failed and if it only has 1 record id, it will populate the record Id. This allows a formula to be used to link to the record.</description>
    <label>Record Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/KicksawEng__IntegrationExecution__c/fields/Retries_Attempted__c.field-meta.xml
<CustomField>
    <fullName>Retries_Attempted__c</fullName>
    <label>Retries Attempted</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/KicksawEng__IntegrationExecution__c/fields/Retry_Ids__c.field-meta.xml
<CustomField>
    <fullName>Retry_Ids__c</fullName>
    <inlineHelpText>Comma-separated list of Record Ids to Retry</inlineHelpText>
    <label>Retry Ids</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/IntegrationExecutionRetryTestHelper.cls
@isTest
public without sharing class IntegrationExecutionRetryTestHelper extends RetryIntegrationAbstractQueuable {
  public override void initRetry(
    KicksawEng__IntegrationExecution__c execution,
    Set<Id> recordIds,
    KicksawEng__IntegrationExecution__c retryParentExecution
  ) {
    super.initializeVarRetry(execution, recordIds, retryParentExecution);
  }

  public override void init(
    KicksawEng__IntegrationExecution__c execution,
    Set<Id> recordIds
  ) {
    super.initializeVar(execution, recordIds);
  }

  public override void processRecords() {
    KicksawEng__IntegrationLog__c log = new KicksawEng__IntegrationLog__c();
    Set<Id> failedRecordIds = new Set<Id>{ 'a3eE10000005AUzIAM' };
    List<KicksawEng__IntegrationLog__c> logs = new List<KicksawEng__IntegrationLog__c>();

    HttpRequest req = new HttpRequest();
    req.setEndpoint('https://www.test.com');
    req.setMethod('GET');
    HttpResponse res = new Http().send(req);

    //Create an exception
    try {
      Decimal num = 1 / 0;
    } catch (Exception e) {
      log = KicksawIntegration.createExceptionLogs(e);
      logs.add(log);
    }

    //Process the execution record and logs
    List<KicksawEng__IntegrationExecution__c> executionsToUpsert = new List<KicksawEng__IntegrationExecution__c>();

    if (failedRecordIds.size() > 0) {
      String retryIdsStr = String.join(failedRecordIds, ',');
      execution.Retry_Ids__c = retryIdsStr;
      if (failedRecordIds.size() == 1) {
        execution.Record_Id__c = failedRecordIds.iterator().next();
      }

      if (retryParentExecution != null) {
        retryParentExecution.KicksawEng__SuccessfulCompletion__c = false;
        retryParentExecution.Retries_Attempted__c = 1;
        executionsToUpsert.add(retryParentExecution);
      }
    } else {
      execution.KicksawEng__SuccessfulCompletion__c = true;
      execution.Next_Retry_Scheduled__c = null;
      if (retryParentExecution != null) {
        retryParentExecution.KicksawEng__SuccessfulCompletion__c = true;
        executionsToUpsert.add(retryParentExecution);
      }
    }

    executionsToUpsert.add(execution);
    upsert executionsToUpsert;

    if (logs.size() > 0) {
      for (KicksawEng__IntegrationLog__c eachlog : logs) {
        eachlog.KicksawEng__IntegrationExecution__c = execution.Id;
      }
      insert logs;
    }
  }
}