force-app/main/default/objects/KicksawEng__IntegrationExecution__c/fields/Next_Retry_Scheduled__c.field-meta.xml
<CustomField>
    <fullName>Next_Retry_Scheduled__c</fullName>
    <label>Next Retry Scheduled</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/KicksawEng__IntegrationExecution__c/fields/Retries_Attempted__c.field-meta.xml
<CustomField>
    <fullName>Retries_Attempted__c</fullName>
    <label>Retries Attempted</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/KicksawEng__IntegrationExecution__c/fields/Retry_Ids__c.field-meta.xml
<CustomField>
    <fullName>Retry_Ids__c</fullName>
    <inlineHelpText>Comma-separated list of Record Ids to Retry</inlineHelpText>
    <label>Retry Ids</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/QueueablePostRetryProcessing.cls
public with sharing class QueueablePostRetryProcessing implements Queueable {
  public KicksawEng__IntegrationExecution__c retryParentExecution;
  public Set<Id> failedRetryRecordIds;

  public QueueablePostRetryProcessing(
    KicksawEng__IntegrationExecution__c retryParentExecution,
    Set<Id> failedRetryRecordIds
  ) {
    this.retryParentExecution = retryParentExecution;
    this.failedRetryRecordIds = failedRetryRecordIds;
  }

  public void execute(QueueableContext context) {
    if (
      retryParentExecution.Retries_Attempted__c <
      retryParentExecution.KicksawEng__Integration__r.Maximum_Retries__c
    ) {
      retryParentExecution.Next_Retry_Scheduled__c = Datetime.now()
        .addMinutes(
          Integer.valueOf(
            retryParentExecution.KicksawEng__Integration__r.Retry_Interval__c
          )
        );
    }

    //Update the original execution with the retry ids that failed again
    retryParentExecution.Retry_Ids__c = String.join(
      new List<Id>(failedRetryRecordIds),
      ','
    );

    update retryParentExecution;
  }
}