force-app/main/default/objects/KicksawEng__Integration__c/fields/Apex_Class_for_Retry__c.field-meta.xml
<CustomField>
    <fullName>Apex_Class_for_Retry__c</fullName>
    <inlineHelpText>API name of the Apex Class that the records will be used for retry. This Apex class needs to extend the RetryIntegrationAbstractQueuable class</inlineHelpText>
    <label>Apex Class for Retry</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/KicksawEng__Integration__c/fields/Enable_Retry__c.field-meta.xml
<CustomField>
    <fullName>Enable_Retry__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Enable Retry</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/KicksawEng__Integration__c/fields/Maximum_Retries__c.field-meta.xml
<CustomField>
    <fullName>Maximum_Retries__c</fullName>
    <inlineHelpText>This is the number of retries to attempt</inlineHelpText>
    <label>Maximum Retries</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/KicksawEng__Integration__c/fields/Retry_Interval__c.field-meta.xml
<CustomField>
    <fullName>Retry_Interval__c</fullName>
    <inlineHelpText>Duration between retries, need to be in increment of 15 minutes.</inlineHelpText>
    <label>Retry Interval</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/KicksawEng__Integration__c/fields/Status_Codes_to_Retry__c.field-meta.xml
<CustomField>
    <fullName>Status_Codes_to_Retry__c</fullName>
    <inlineHelpText>Comma-separated list of HTTP status codes to retry the execution e.g. 400,408,429</inlineHelpText>
    <label>Status Codes to Retry</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/KicksawEng__IntegrationExecution__c/fields/Next_Retry_Scheduled__c.field-meta.xml
<CustomField>
    <fullName>Next_Retry_Scheduled__c</fullName>
    <label>Next Retry Scheduled</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/KicksawEng__IntegrationExecution__c/fields/Retry_Ids__c.field-meta.xml
<CustomField>
    <fullName>Retry_Ids__c</fullName>
    <inlineHelpText>Comma-separated list of Record Ids to Retry</inlineHelpText>
    <label>Retry Ids</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/BatchIntegrationExecutionRetryTest.cls
@isTest
public without sharing class BatchIntegrationExecutionRetryTest {
  @TestSetup
  static void makeData() {
    KicksawEng__Integration__c integration = new KicksawEng__Integration__c(
      Name = 'Test Integration',
      Apex_Class_for_Retry__c = 'IntegrationExecutionRetryTestHelper',
      Enable_Retry__c = true,
      Maximum_Retries__c = 3,
      Retry_Interval__c = 15,
      Status_Codes_to_Retry__c = '400,500'
    );

    insert integration;

    KicksawEng__IntegrationExecution__c execution = new KicksawEng__IntegrationExecution__c(
      KicksawEng__Integration__c = integration.Id,
      Next_Retry_Scheduled__c = Datetime.now(),
      Retry_Ids__c = 'a3eE10000005AUzIAM,a2eE10000005AUzIAM'
    );

    insert execution;

    KicksawEng__IntegrationLog__c log = new KicksawEng__IntegrationLog__c(
      KicksawEng__IntegrationExecution__c = execution.Id,
      KicksawEng__StatusCode__c = 500
    );
    insert log;
  }

  @isTest
  public static void testRetry() {
    MockRequestSingle mockCallout = new MockRequestSingle(
      200,
      'Success',
      '{"success": true}',
      null
    );

    Test.setMock(HttpCalloutMock.class, mockCallout);
    Test.startTest();

    BatchIntegrationExecutionRetry retryBatch = new BatchIntegrationExecutionRetry();
    Database.executeBatch(retryBatch, 100);
    Test.stopTest();
  }

  @isTest
  public static void schedulableTest() {
    Test.startTest();
    BatchIntegrationExecutionRetry retryBatch = new BatchIntegrationExecutionRetry();
    String jobId = System.schedule(
      'BatchIntegrationExecutionRetry',
      '0 0 0 15 3 ?',
      retryBatch
    );
    Test.stopTest();

    //Check that job has been scheduled
    System.assertEquals(1, [SELECT COUNT() FROM CronTrigger WHERE Id = :jobId]);
  }
}